
; 多语言设置
[LanguageSetting]
; 文字出现基础速度
TextSpeed = 10

; 自动播放时，每句等待时间
AutoWaitTime  = 1.75


;不同语言语速倍数，默认1倍
multi_zh_CN = 1
multi_zh_TW = 1
multi_ja_JP = 2.7
multi_ko_KR = 2.7
multi_en_US = 1.3
multi_de_DE = 1.2
multi_fr_FR = 1.1
multi_es_ES = 1.2
multi_id_ID = 1.1
multi_th_TH = 1.1





; 配置语言每次弹几个字，默认1
; 英语 每次弹3个字符
unit_en_US = 3		
	
; 德语 每次弹3个字符
unit_de_DE = 3

; 法语 每次弹3个字符
unit_fr_FR = 3 

; 西语 每次弹3个字符
unit_es_ES = 3

; 泰语 每次弹3个字符
unit_th_TH = 3

; 印尼语 每次弹3个字符
unit_id_ID = 3


; 战斗场景 npc对话参数配置
[FightNpcTalk]
Angle = 135
Length = 150
Height = 45
LookTargetHeight = 60
TitleAppearDis = 5000