[global]

; 总共有多少点
player_pos_count = 3
player_pos1 = 150,0,0
player_pos2 = 120,0,0
player_pos3 = 100,0,0


; 动画播放类型说明
; custom_seq 		: 播放所有动画，不循环
; custom_loop 		: 循环播放动画，每次从头开始循环
; custom_loop_last	: 循环播放动画，只循环播放最后一个