[global]
; 卡牌绑定的物件
barrier_objectId = 3013
landmine_objectId = 3006
explosive_objectId = 3007
missile_objectId = 3010


; 使用清扫卡时 播放的 特效id 和 barrier 被触发时播放的特效id
removeCardEffectId = 9
barrierTriggerEffectId = 17 
telephoneEffectId = 17


; 道具战斗 金钱损失
landmine_money = -1555
explosive_money = -1111
missile_money = -888


; 道具卡的模板id
freecardTpl = 8
transfercardTpl = 7

; 建筑组
build_group_1 = 4001,4002,4003,4004
build_group_2 = 4008,4009,4010
build_group_3 = 4014,4015,4016

; 有多少建筑组
build_group = 3

; 空地块id，支持列表
empty_ground_id  = 4001

; 建筑底座id，支持列表
build_bottom_id  = 5001,5002

; 缩小时的缩放
small_scale = 0.75

; 物价上涨时，建筑购买价格增加倍数
building_buy_multi = 1.2

; 物价上涨时，建筑升级价格增加倍数
building_levelup_multi = 1.2

; 物价上涨时，建筑租金价格增加倍数
building_toll_multi = 2

; npc到新格子时，买房概率（最高100）
npc_buy_rate = 100

; npc到新格子时，升级房子概率（最高100）
npc_levelup_rate = 100