
;------------------------------------------
; 定义变量类型
;------------------------------------------
define var {key=bool, 			name=开关}
define var {key=float, 			name=浮点数}
define var {key=int, 			name=整数}
define var {key=string, 		name=字符串}
define var {key=obj_id, 		name=物件id}
define var {key=obj_tag, 		name=物件tag}
define var {key=custom_event_id, name=自定义事件}

define var {key=grid_id, 		name=格子id}
define var {key=grid_id_list, 	name=格子id列表}
define var {key=effect_tplid, 	name=特效, 	    type="file_options", 	file="14_effects.txt"}
define var {key=npc_tplid, 		name=Npc, 	    type="file_options", 	file="02_npcs.txt"}
define var {key=drop_tplid, 	name=掉落Id, 	    type="file_options", 	file="03_drop.txt"}

define var {key=drop,           name=下拉列表,    type=options}
	add option {id = 1, name="S自己", tip="注释"}
	add option {id = 2, name="S技能释放者"}

define var {key=msg_type,           name=消息类型,    type=options}
	add option {id = 1, name="Info", tip="白色输出"}
	add option {id = 2, name="Error", tip="红色错误消息"}
	add option {id = 3, name="Message", tip="消息弹框"}


define var {key=dir_type,           name=方向类型,    type=multi_options}
	add option {id = 1, name="上边", 	tip="上边"}
	add option {id = 2, name="下边", 	tip="下边"}
	add option {id = 3, name="左边", 	tip="左边"}
	add option {id = 4, name="右边", 	tip="右边"}

;------------------------------------------
; 定义类
;------------------------------------------
define class {key="class_born",    		name="出生点"}

define class {key="class_spawn_npc",    name="刷怪器"}
    add param {type="npc_tplid", 		key="npc_id",   	name="NpcId",		tip = "怪物模板Id"}
    add param {type="string", 			key="interval",   	name="刷新间隔",	tip = "每隔多少秒刷出一只"}
	add param {type="string", 			key="delay",   		name="首次延迟", 	tip = "单位秒"}
	add param {type="string", 			key="max",   		name="最大数量",	tip = "最大刷多少只怪"}

define class {key="class_road_dir",    	name="寻路方向"}
    add param {type="dir_type", 		key="dir",   		name="寻路方向", 	tip = "可以选多个"}
	
define class {key="class_random_item",	name="随机道具"}
    add param {type="drop_tplid", 		key="random_item",  name="随机道具", 	tip = "对应drop表"}

define class {key="class_house",		name="房子"}
    add param {type="int", 				key="group_ip",  	name="房子配置", 	tip = "对应house表"}

define class {key="class_flip_game",    name="翻盘游戏"}

define class {key="class_bomb",			name="炸弹"}
    add param {type="int", 				key="rest_days",  		name="休息回合", tip = "配置回合数+1 比如休息一回合就配2"}
    add param {type="int", 				key="effect_id",  		name="特效ID", 	tip = "对应04_effects.txt"}

define class {key="class_hospital",			name="医院"}
    add param {type="grid_id", 				key="pos_id",  			name="出院点ID", tip = "出院点的位置"}
	
define class {key="class_building",			name="建筑"}
    add param {type="grid_id_list", 		key="ids",  			name="有效位置", tip = "哪些位置可以买"}
	
define class {key="class_transfer",			name="传送门"}
    add param {type="grid_id", 				key="id",  				name="传送位置", tip = "传送到哪个位置"}
	add param {type="dir_type", 			key="dir",  			name="朝向", tip = "朝向"}
	
;------------------------------------------
; 定义事件
;------------------------------------------
define event {key="CTE_OnGameInit", 		    name="当首次进入游戏时"}
define event {key="CTE_OnGameStart", 		    name="当游戏开始时"}
define event {key="CTE_OnEntryRegion", 		    name="当进入区域时"}
	def meta {desc="当进入区域{{id}}时" }
	add param {type="string", 	    			key="id", 		    	name="区域id", 		tip="不填表示自身"}

define event {key="CTE_OnEntryGrid", 	    	name="当经过格子时", 	tip="当经过格子时"}
	def meta {desc="当经过格子时" }
	add param {type="grid_id_list", 	    	key="id", 		    	name="格子",  		tip="不填表示自身"}

define event {key="CTE_OnReachGrid", 	    	name="当到达格子时", 	tip="当到达格子时"}
	def meta {desc="当到达格子时" }
	add param {type="grid_id_list", 	    	key="id", 		    	name="格子",  		tip="不填表示自身"}

;------------------------------------------
; 定义条件
;------------------------------------------
define condition {key="CTC_Test", 		name="测试条件"}
	def meta {desc="测试条件{{id}}" }
	add param {type="string", 	    			key="id", 		    	name="区域id", 		tip="不填表示自身"}


;------------------------------------------
; 定义事件触发后的行为
;------------------------------------------
define action {key="CTA_WaitTime",    name="等待一段时间"}
	def meta {category="常用",  	desc="等待 {{time}} 秒" }
	add param {type="float", 		key="time",   name="秒"}

define action {key="CTA_Print",    name="调试输出"}
	def meta {category="常用",  	desc="输出: {{value}}" }
	add param {type="string", 		key="value",   name="内容"}
	add param {type="msg_type", 	key="type",   name="类型"}

define action {key="CTA_PlayEffect",    name="播放特效"}
	def meta {category="常用",  	desc="播放特效: {{eff_id}}" }
	add param {type="string", 		key="eff_id",   name="特效id"}

define action {key="CTA_PlayAudio",    name="播放声音"}
	def meta {category="常用",  	desc="播放声音: {{audio_id}}" }
	add param {type="string", 		key="audio_id",   name="声音id"}

define action {key="CTA_SendEvent",    name="发送自定义事件"}
	def meta {category="常用",  	desc="发送自定义事件: {{name}}" }
	add param {type="custom_event_id", 	key="name",   name="事件名"}